/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111281-g285c7f6f6b-20230627"
#endif /* AVUTIL_FFVERSION_H */
